### ISSUE TITLE
SIMPA Definition of MSOT inVision system has the wrong radius

### ISSUE THREAD

**Issue by tre26** [IMSY-DKFZ/simpa#126]
[Link here to code](https://github.com/IMSY-DKFZ/simpa/blob/main/simpa/core/device_digital_twins/pa_devices/ithera_msot_invision.py#L43
)
The correct radius for the MSOT inVision should be 0.0405 m as far as I know. This is the value specified in the metadata from the study acquisitions anyway.

**Comment by kdreher** [comment]
I think we originally modelled it after [this paper](https://doi.org/10.1117/1.JBO.19.3.036021) in which the radius is 40 mm. However, the pitch seems to be 0.735 mm instead of 0.74 mm. So there is definitely still something wrong. Maybe they updated the device with another radius or pitch. 
We should ask iThera directly to clarify that.

**Comment by jgroehl** [comment]
I'm pretty sure I modeled it based on a technical drawing I received from iThera.
I'll look into it again!

**Comment by jgroehl** [comment]
We contacted iThera and they sent us the details again. Indeed, the pitch is 0.735 instead of 0.74, but the radius seems correct!
