### ISSUE TITLE
Reconstruction volume dimensions not mandatory

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#127]
Currently, when using the reconstruction convenience function, the `Tags.DIM_VOLUME_{X|Y|Z}_MM` need to be set, because the reconstruction algorithm calls `check_settings_prerequisites` which internally requires these settings to be set.

However, when only using the convenience function for reconstruction, this check is not necessary and therefore setting the volume dimensions should not be required.

Is it possible to leave out the `check_settings_prerequisites` call within the reconstruction algorithms?

**Comment by Holzwarth69126** [comment]
If Tags.DIM_VOLUME_{X|Y|Z}_MM is set 0 the following Error occurs:
"ERROR - Volume z dimension is too small to encompass the device in simulation! Must be at least 22.278930105510916 mm but was 0 mm" 
--> Reconstruction works anyway. Otherwise the error should break the reconstruction or be at least more visible.

**Comment by jgroehl** [comment]
Yes, it should be possible.
We call `check_settings_prerequisites` once at the beginning of a full simulation pipeline anyway and for the image reconstruction algorithm, these constraints should not matter at all.
