### ISSUE TITLE
Rewrite structure creation for use of GPU

### ISSUE THREAD

**Issue by kdreher** [IMSY-DKFZ/simpa#166]
Rewrite all the vector and matrix operations used during the creation of [structures](https://github.com/IMSY-DKFZ/simpa/tree/main/simpa/utils/libraries/structure_library) with pytorch instead of numpy. Then, the GPU can be used for computationally expensive operations.

**Comment by TomTomRixRix** [comment]
See also #152

**Comment by TomTomRixRix** [comment]
@kdreher I've just timed how much performance gain we get when switching from numpy on CPU to pytorch with GPU processing. Based on the tissue created in the `minimal_optical_simulation.py` with only the vessel structure I receive the following results:

Numpy (CPU): 0.3 s
PyTorch (CPU): 0.23 s, 0.21 s 
PyTorch (GPU): 1.75 s, 0.039 s

Even without using the GPU, performing the processing with PyTorch is faster. When using a GPU, the creation on the first wavelength takes significantly longer (I guess due to the initialization issue of PyTorch). One this is done, the processing is an order of magnitude faster.

**Comment by TomTomRixRix** [comment]
I've now implemented the pytorch version for all structures (except of the background as creating a tensor of ones and converting it to a numpy array should not be faster than creating the numpy array directly) on branch `T166_StructuresWithGPU`.

When comparing the absorbtion coefficient of the minimal example with all structures between the numpy and pytorch version, all pixels were identical except of one with a relatively large difference. Might this be due to some seeding issue or some partial volume effect?

While implementing the changes I noticed two things to consider:
1. Is there any seeding done for creating the structures? If yes, we should make sure that it also works properly for torch.
2. Do we create the structures with float or double precision, or does it not matter for this purpose?

**Comment by TomTomRixRix** [comment]
> 1. Is there any seeding done for creating the structures? If yes, we should make sure that it also works properly for torch.

Currently the volume generation only needs seeding for the vessel structures (sampling from uniform distribution). As this is still done in numpy, currently no torch seeding is required.

> 2. Do we create the structures with float or double precision, or does it not matter for this purpose?

We decided to use float, i.e. torch.float32 for the structures as the precision should be enough and speed is more important

**Comment by kdreher** [comment]
closed by #175
